name: scout
description: "Spiritual Care Operations & Usage Tracker"
publish_to: 'none'

version: 1.0.57

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  google_fonts: ^6.2.1
  mobile_scanner: ^7.0.1
  web: ^1.1.1
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  shared_preferences: ^2.3.2
  http: ^1.5.0
  algolia_helper_flutter: ^1.2.0
  infinite_scroll_pagination: ^5.0.0
  algoliasearch: ^1.36.1
  intl: ^0.19.0
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.1.20
  file_picker: ^10.3.3
  image_picker: ^1.1.2
  uuid: ^4.4.0
  pdf: ^3.10.7
  qr_flutter: ^4.1.0
  qr: ^3.0.1
  image: ^4.0.21
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  flutter_typeahead: ^5.2.0
  go_router: ^6.0.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  # url_strategy removed (package discontinued); using flutter_web_plugins for path URL strategy
  flutter_web_plugins:
    sdk: flutter
  dart_firebase_admin: ^0.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/images/scout dash logo light mode.png
  image_dark: assets/images/scout dash logo dark mode.png





















